# Generated by Django 2.2.1 on 2019-06-25 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_auto_20190618_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creat_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Refused', 'Refused'), ('Pendind', 'Pending'), ('Aproved', 'Aproved')], default='Pending', max_length=58)),
                ('shipment', models.CharField(choices=[('Packing', 'Packing'), ('Pendind', 'Pending'), ('Posted', 'Posted'), ('Delivered', 'Delivered')], default='Pending', max_length=58)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_merchant', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_product', to='portal.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
